name: Integration Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  integration-test:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Compose version
        run: |
          docker compose version
          docker version

      - name: Build and run
        env:
          COMPOSE_PROFILES: integration-test
        run: |
          set -euxo pipefail
          cd integration-test/go-client
          go mod vendor
          cd ..
          docker compose --profile integration-test up --build --exit-code-from=smoke-test

      - name: Dump logs on failure
        if: failure()
        run: |
          echo "==== docker compose ps ===="
          docker compose ps || true
          echo "==== docker compose logs ===="
          docker compose logs --no-color || true

      - name: Tear down
        if: always()
        run: |
          docker compose down -v --remove-orphans || true
